name: lamarr
services:
  app:
    deploy:
      resources:
        limits:
          memory: 512M
    restart: unless-stopped
    build: .
    env_file: .env
    environment:
      API_ADDR: "127.0.0.1:8080"
      DB_USERNAME: "lamarr"
      DB_PASSWORD: "password"
      DB_HOSTNAME: "db"
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres:alpine
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "lamarr"
    volumes:
      - lamarr-db:/var/lib/postgresql/data

volumes:
  lamarr-db:
    external: true
