name: lamarr
services:
  app:
    deploy:
      resources:
        limits:
          memory: 256M
    restart: unless-stopped
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:alpine
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "lamarr"
    volumes:
      - lamarr-db:/var/lib/postgresql/data

volumes:
  lamarr-db:
