apiVersion: v1
kind: ConfigMap
metadata:
  name: module-config-map
data:
  APP_NAME: "Module"
  LOG_LEVEL: "error"
  DEBUG: "false"
  API_ADDR: "0.0.0.0:7000"
  DISCORD_OWNER_ID: ""
  DISCORD_GUILD_ID: ""
  DB_DATABASE: "module"
  DB_HOSTNAME: "127.0.0.1"
  DB_PORT: "5432"

---
apiVersion: v1
kind: Secret
metadata:
  name: module-secrets
data:
  DISCORD_TOKEN: base64
  DB_USERNAME: base64
  DB_PASSWORD: ""

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: module-deployment
  labels:
    app: module
spec:
  selector:
    matchLabels:
      app: module
  template:
    metadata:
      labels:
        app: module
    spec:
      containers:
        - name: module
          image: localhost:5000/module
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 7000
          envFrom:
            - configMapRef:
                name: module-config-map
            - secretRef:
                name: module-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: module-service
spec:
  selector:
    app: module
  ports:
    - port: 7000
      targetPort: 7000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: module-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: module-service
                port:
                  number: 80
